/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Transaction.java
 *
 * Created on 23 Jan 13, 15:08:46
 */
package form;

import db.Parameter;
import db.ResultSetTableModel;
import db.db_connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Seno4
 */
public class Transaction extends javax.swing.JFrame {

    ResultSet rs;
    db_connection db;
    int old, dec, now;
    String newstock;

    /** Creates new form Transaction */
    @SuppressWarnings("static-access")
    public Transaction() {
        db = new db_connection(new Parameter().HOST_DB, new Parameter().USERNAME_DB, new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        initComponents();
        table();
        jam();
    }

    public void table() {
        String namaKolom[] = {"Code", "Title", "Author", "Publisher", "Price", "Discount", "Stock"};
        rs = db.querySelect(namaKolom, "books_data");
        tbl_result.setModel(new ResultSetTableModel(rs));
    }

    public void tampil_chart() {
        String namaKolom[] = {"ID", "Invoice", "Code", "Title", "Cost", "Amount", "Subtotal"};
        rs = db.fcSelectCommand(namaKolom, "chart", "Invoice='" + txt_invoice.getText() + "'");
        tbl_chart.setModel(new ResultSetTableModel(rs));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new usu.widget.Panel();
        panelGlass1 = new usu.widget.glass.PanelGlass();
        panelGlass2 = new usu.widget.glass.PanelGlass();
        txt_search = new usu.widget.TextBox();
        btn_search = new usu.widget.ButtonGlass();
        label1 = new usu.widget.Label();
        cmb_categories = new javax.swing.JComboBox();
        txt_code = new usu.widget.TextBox();
        label2 = new usu.widget.Label();
        label3 = new usu.widget.Label();
        txt_title = new usu.widget.TextBox();
        label4 = new usu.widget.Label();
        label5 = new usu.widget.Label();
        txt_author = new usu.widget.TextBox();
        txt_publisher = new usu.widget.TextBox();
        label6 = new usu.widget.Label();
        label7 = new usu.widget.Label();
        txt_price = new usu.widget.TextBox();
        txt_discount = new usu.widget.TextBox();
        label8 = new usu.widget.Label();
        txt_cost = new usu.widget.TextBox();
        label9 = new usu.widget.Label();
        txt_amount = new usu.widget.TextBox();
        panelGlass4 = new usu.widget.glass.PanelGlass();
        label10 = new usu.widget.Label();
        lbl_subtotal = new usu.widget.Label();
        label12 = new usu.widget.Label();
        btn_chart = new usu.widget.ButtonGlass();
        btn_cancel = new usu.widget.ButtonGlass();
        panelGlass3 = new usu.widget.glass.PanelGlass();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_result = new javax.swing.JTable();
        panelGlass7 = new usu.widget.glass.PanelGlass();
        label13 = new usu.widget.Label();
        panelGlass6 = new usu.widget.glass.PanelGlass();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_chart = new javax.swing.JTable();
        panelGlass8 = new usu.widget.glass.PanelGlass();
        label14 = new usu.widget.Label();
        panelGlass10 = new usu.widget.glass.PanelGlass();
        label16 = new usu.widget.Label();
        lbl_total = new usu.widget.Label();
        label18 = new usu.widget.Label();
        panelGlass12 = new usu.widget.glass.PanelGlass();
        label20 = new usu.widget.Label();
        panelGlass13 = new usu.widget.glass.PanelGlass();
        label19 = new usu.widget.Label();
        txt_invoice = new usu.widget.TextBox();
        label15 = new usu.widget.Label();
        txt_cash = new usu.widget.TextBox();
        panelGlass14 = new usu.widget.glass.PanelGlass();
        label21 = new usu.widget.Label();
        panelGlass15 = new usu.widget.glass.PanelGlass();
        label22 = new usu.widget.Label();
        panelGlass16 = new usu.widget.glass.PanelGlass();
        label23 = new usu.widget.Label();
        panelGlass17 = new usu.widget.glass.PanelGlass();
        label24 = new usu.widget.Label();
        panelGlass18 = new usu.widget.glass.PanelGlass();
        label25 = new usu.widget.Label();
        txt_payback = new usu.widget.TextBox();
        txt_deinvoice = new usu.widget.ButtonGlass();
        btn_print = new usu.widget.ButtonGlass();
        btn_delete = new usu.widget.ButtonGlass();
        btn_delete1 = new usu.widget.ButtonGlass();
        lbl_time = new usu.widget.Label();
        lbl_date = new usu.widget.Label();
        btn_logout = new usu.widget.ButtonGlass();
        btn_refresh = new usu.widget.ButtonGlass();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cashier Sasa Book Store");
        setFocusable(false);

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/Image/background_home_2.png"))); // NOI18N
        panel1.setPreferredSize(new java.awt.Dimension(1280, 800));

        panelGlass1.setBackground(new java.awt.Color(0, 0, 0));
        panelGlass1.setRound(false);
        panelGlass1.setWarna(new java.awt.Color(0, 0, 0));

        panelGlass2.setRound(false);
        panelGlass2.setWarna(new java.awt.Color(255, 0, 255));

        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button_search.png"))); // NOI18N
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Search Categories:");
        label1.setFont(new java.awt.Font("Ubahn", 0, 18));

        cmb_categories.setFont(new java.awt.Font("Ubahn", 0, 18));
        cmb_categories.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Code", "Title", "Author", "Publisher", "Price", "Discount", "Stock" }));
        cmb_categories.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        txt_code.setFont(new java.awt.Font("Gisha", 0, 12));

        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Code");
        label2.setFont(new java.awt.Font("Gisha", 0, 14));

        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Title");
        label3.setFont(new java.awt.Font("Gisha", 0, 14));

        txt_title.setFont(new java.awt.Font("Gisha", 0, 12));

        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("Publisher");
        label4.setFont(new java.awt.Font("Gisha", 0, 14));

        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("Author");
        label5.setFont(new java.awt.Font("Gisha", 0, 14));

        txt_author.setFont(new java.awt.Font("Gisha", 0, 12));
        txt_author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_authorActionPerformed(evt);
            }
        });

        txt_publisher.setFont(new java.awt.Font("Gisha", 0, 12));

        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setText("Discount%");
        label6.setFont(new java.awt.Font("Gisha", 0, 14));

        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setText("Price");
        label7.setFont(new java.awt.Font("Gisha", 0, 14));

        txt_price.setFont(new java.awt.Font("Gisha", 0, 12));
        txt_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_priceActionPerformed(evt);
            }
        });

        txt_discount.setFont(new java.awt.Font("Gisha", 0, 12));

        label8.setForeground(new java.awt.Color(255, 255, 255));
        label8.setText("Cost");
        label8.setFont(new java.awt.Font("Gisha", 0, 14));

        txt_cost.setFont(new java.awt.Font("Gisha", 0, 12));

        label9.setForeground(new java.awt.Color(255, 255, 255));
        label9.setText("Amount");
        label9.setFont(new java.awt.Font("Gisha", 0, 14));

        txt_amount.setFont(new java.awt.Font("Gisha", 0, 12));
        txt_amount.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_amountInputMethodTextChanged(evt);
            }
        });
        txt_amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_amountKeyReleased(evt);
            }
        });

        panelGlass4.setRound(false);
        panelGlass4.setWarna(new java.awt.Color(255, 255, 0));

        label10.setForeground(new java.awt.Color(255, 255, 255));
        label10.setText("Rp.");
        label10.setFont(new java.awt.Font("Ubahn", 1, 18));

        lbl_subtotal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_subtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_subtotal.setText("0");
        lbl_subtotal.setFont(new java.awt.Font("Tahoma", 1, 18));

        label12.setForeground(new java.awt.Color(255, 255, 255));
        label12.setText(",-");
        label12.setFont(new java.awt.Font("Tahoma", 1, 18));

        javax.swing.GroupLayout panelGlass4Layout = new javax.swing.GroupLayout(panelGlass4);
        panelGlass4.setLayout(panelGlass4Layout);
        panelGlass4Layout.setHorizontalGroup(
            panelGlass4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        panelGlass4Layout.setVerticalGroup(
            panelGlass4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(label10, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addComponent(lbl_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn_chart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button_addtochart.png"))); // NOI18N
        btn_chart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chartActionPerformed(evt);
            }
        });

        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button_cancel.png"))); // NOI18N

        javax.swing.GroupLayout panelGlass2Layout = new javax.swing.GroupLayout(panelGlass2);
        panelGlass2.setLayout(panelGlass2Layout);
        panelGlass2Layout.setHorizontalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass2Layout.createSequentialGroup()
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmb_categories, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelGlass2Layout.createSequentialGroup()
                        .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGlass2Layout.createSequentialGroup()
                                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label6, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_discount, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(txt_price, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(txt_publisher, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(txt_author, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(txt_code, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(txt_cost, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(txt_title, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(txt_amount, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                    .addGroup(panelGlass2Layout.createSequentialGroup()
                        .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addGap(164, 164, 164))
                    .addComponent(panelGlass4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelGlass2Layout.createSequentialGroup()
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btn_chart, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelGlass2Layout.setVerticalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_categories, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_search, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addComponent(txt_search, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_publisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelGlass4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        panelGlass3.setRound(false);
        panelGlass3.setWarna(new java.awt.Color(255, 0, 255));

        tbl_result.setFont(new java.awt.Font("Segoe UI", 0, 14));
        tbl_result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Title", "Author", "Publisher", "Pricel", "Discount", "Stock"
            }
        ));
        tbl_result.setGridColor(new java.awt.Color(0, 204, 0));
        tbl_result.setSelectionBackground(new java.awt.Color(0, 153, 51));
        tbl_result.setSelectionForeground(new java.awt.Color(204, 204, 204));
        tbl_result.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_resultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_result);

        panelGlass7.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/Image/table_header_green.png"))); // NOI18N
        panelGlass7.setPreferredSize(new java.awt.Dimension(890, 36));

        label13.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        label13.setForeground(new java.awt.Color(255, 255, 255));
        label13.setText("Result");
        label13.setFont(new java.awt.Font("Ubahn", 0, 18));

        javax.swing.GroupLayout panelGlass7Layout = new javax.swing.GroupLayout(panelGlass7);
        panelGlass7.setLayout(panelGlass7Layout);
        panelGlass7Layout.setHorizontalGroup(
            panelGlass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass7Layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(427, Short.MAX_VALUE))
        );
        panelGlass7Layout.setVerticalGroup(
            panelGlass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass7Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGlass3Layout = new javax.swing.GroupLayout(panelGlass3);
        panelGlass3.setLayout(panelGlass3Layout);
        panelGlass3Layout.setHorizontalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
                    .addComponent(panelGlass7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        panelGlass3Layout.setVerticalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGlass7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelGlass6.setRound(false);
        panelGlass6.setWarna(new java.awt.Color(255, 0, 255));

        tbl_chart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Code", "Title", "Cost", "Amount", "Subtotal"
            }
        ));
        jScrollPane2.setViewportView(tbl_chart);

        panelGlass8.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/Image/table_header_blue.png"))); // NOI18N
        panelGlass8.setRound(false);

        label14.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        label14.setForeground(new java.awt.Color(255, 255, 255));
        label14.setText("Chart");
        label14.setFont(new java.awt.Font("Ubahn", 0, 18));

        javax.swing.GroupLayout panelGlass8Layout = new javax.swing.GroupLayout(panelGlass8);
        panelGlass8.setLayout(panelGlass8Layout);
        panelGlass8Layout.setHorizontalGroup(
            panelGlass8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass8Layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );
        panelGlass8Layout.setVerticalGroup(
            panelGlass8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass8Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        panelGlass10.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/Image/table_header_blue.png"))); // NOI18N
        panelGlass10.setRound(false);

        label16.setForeground(new java.awt.Color(255, 255, 255));
        label16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label16.setText(",-");
        label16.setFont(new java.awt.Font("Tahoma", 1, 18));

        lbl_total.setForeground(new java.awt.Color(255, 255, 255));
        lbl_total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_total.setText("0");
        lbl_total.setFont(new java.awt.Font("Tahoma", 1, 18));

        label18.setForeground(new java.awt.Color(255, 255, 255));
        label18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label18.setText("Rp.");
        label18.setFont(new java.awt.Font("Tahoma", 1, 18));

        javax.swing.GroupLayout panelGlass10Layout = new javax.swing.GroupLayout(panelGlass10);
        panelGlass10.setLayout(panelGlass10Layout);
        panelGlass10Layout.setHorizontalGroup(
            panelGlass10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGlass10Layout.setVerticalGroup(
            panelGlass10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(label16, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addComponent(lbl_total, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addComponent(label18, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        panelGlass12.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/Image/table_header_lumut.png"))); // NOI18N
        panelGlass12.setPreferredSize(new java.awt.Dimension(60, 24));
        panelGlass12.setRound(false);

        label20.setForeground(new java.awt.Color(255, 255, 255));
        label20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label20.setText("Cash");
        label20.setFont(new java.awt.Font("Ubahn", 0, 16));

        javax.swing.GroupLayout panelGlass12Layout = new javax.swing.GroupLayout(panelGlass12);
        panelGlass12.setLayout(panelGlass12Layout);
        panelGlass12Layout.setHorizontalGroup(
            panelGlass12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass12Layout.createSequentialGroup()
                .addComponent(label20, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass12Layout.setVerticalGroup(
            panelGlass12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label20, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        panelGlass13.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/Image/table_header_blue.png"))); // NOI18N
        panelGlass13.setForeground(new java.awt.Color(0, 51, 51));
        panelGlass13.setRound(false);

        label19.setForeground(new java.awt.Color(255, 255, 255));
        label19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label19.setText("Total");
        label19.setFont(new java.awt.Font("Ubahn", 0, 24));

        javax.swing.GroupLayout panelGlass13Layout = new javax.swing.GroupLayout(panelGlass13);
        panelGlass13.setLayout(panelGlass13Layout);
        panelGlass13Layout.setHorizontalGroup(
            panelGlass13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass13Layout.createSequentialGroup()
                .addComponent(label19, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass13Layout.setVerticalGroup(
            panelGlass13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label19, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        txt_invoice.setFont(new java.awt.Font("Ubahn", 0, 14));

        label15.setForeground(new java.awt.Color(255, 255, 255));
        label15.setText("Invoice Number :");
        label15.setFont(new java.awt.Font("Ubahn", 0, 14));

        txt_cash.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_cash.setFont(new java.awt.Font("Ubahn", 0, 18));
        txt_cash.setPreferredSize(new java.awt.Dimension(6, 24));
        txt_cash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cashKeyReleased(evt);
            }
        });

        panelGlass14.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/Image/table_header_lumut.png"))); // NOI18N
        panelGlass14.setRound(false);

        label21.setForeground(new java.awt.Color(255, 255, 255));
        label21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label21.setText(",-");
        label21.setFont(new java.awt.Font("Ubahn", 0, 24));

        javax.swing.GroupLayout panelGlass14Layout = new javax.swing.GroupLayout(panelGlass14);
        panelGlass14.setLayout(panelGlass14Layout);
        panelGlass14Layout.setHorizontalGroup(
            panelGlass14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass14Layout.createSequentialGroup()
                .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass14Layout.setVerticalGroup(
            panelGlass14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label21, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        panelGlass15.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/Image/table_header_lumut.png"))); // NOI18N
        panelGlass15.setRound(false);

        label22.setForeground(new java.awt.Color(255, 255, 255));
        label22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label22.setText("Rp.");
        label22.setFont(new java.awt.Font("Ubahn", 0, 16));

        javax.swing.GroupLayout panelGlass15Layout = new javax.swing.GroupLayout(panelGlass15);
        panelGlass15.setLayout(panelGlass15Layout);
        panelGlass15Layout.setHorizontalGroup(
            panelGlass15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass15Layout.createSequentialGroup()
                .addComponent(label22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass15Layout.setVerticalGroup(
            panelGlass15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label22, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        panelGlass16.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/Image/table_header_red.png"))); // NOI18N
        panelGlass16.setPreferredSize(new java.awt.Dimension(21, 24));
        panelGlass16.setRound(false);

        label23.setForeground(new java.awt.Color(255, 255, 255));
        label23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label23.setText(",-");
        label23.setFont(new java.awt.Font("Ubahn", 0, 24));

        javax.swing.GroupLayout panelGlass16Layout = new javax.swing.GroupLayout(panelGlass16);
        panelGlass16.setLayout(panelGlass16Layout);
        panelGlass16Layout.setHorizontalGroup(
            panelGlass16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass16Layout.createSequentialGroup()
                .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass16Layout.setVerticalGroup(
            panelGlass16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label23, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        panelGlass17.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/Image/table_header_red.png"))); // NOI18N
        panelGlass17.setPreferredSize(new java.awt.Dimension(30, 24));
        panelGlass17.setRound(false);

        label24.setForeground(new java.awt.Color(255, 255, 255));
        label24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label24.setText("Rp.");
        label24.setFont(new java.awt.Font("Ubahn", 0, 16));

        javax.swing.GroupLayout panelGlass17Layout = new javax.swing.GroupLayout(panelGlass17);
        panelGlass17.setLayout(panelGlass17Layout);
        panelGlass17Layout.setHorizontalGroup(
            panelGlass17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass17Layout.createSequentialGroup()
                .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(6, Short.MAX_VALUE))
        );
        panelGlass17Layout.setVerticalGroup(
            panelGlass17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label24, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        panelGlass18.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/Image/table_header_red.png"))); // NOI18N
        panelGlass18.setRound(false);

        label25.setForeground(new java.awt.Color(255, 255, 255));
        label25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label25.setText("Payback");
        label25.setFont(new java.awt.Font("Ubahn", 0, 16));

        javax.swing.GroupLayout panelGlass18Layout = new javax.swing.GroupLayout(panelGlass18);
        panelGlass18.setLayout(panelGlass18Layout);
        panelGlass18Layout.setHorizontalGroup(
            panelGlass18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass18Layout.createSequentialGroup()
                .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(5, Short.MAX_VALUE))
        );
        panelGlass18Layout.setVerticalGroup(
            panelGlass18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label25, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        txt_payback.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_payback.setFont(new java.awt.Font("Ubahn", 0, 18));
        txt_payback.setPreferredSize(new java.awt.Dimension(6, 24));

        txt_deinvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button_cancel.png"))); // NOI18N
        txt_deinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deinvoiceActionPerformed(evt);
            }
        });

        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button_print.png"))); // NOI18N
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button_cancel_small.png"))); // NOI18N
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_delete1.setBackground(new java.awt.Color(255, 255, 255));
        btn_delete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button_search_small.png"))); // NOI18N
        btn_delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass6Layout = new javax.swing.GroupLayout(panelGlass6);
        panelGlass6.setLayout(panelGlass6Layout);
        panelGlass6Layout.setHorizontalGroup(
            panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass6Layout.createSequentialGroup()
                        .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGlass6Layout.createSequentialGroup()
                        .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass6Layout.createSequentialGroup()
                                .addComponent(panelGlass13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelGlass10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelGlass6Layout.createSequentialGroup()
                                .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(panelGlass18, 0, 55, Short.MAX_VALUE)
                                    .addComponent(panelGlass12, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(panelGlass17, 0, 26, Short.MAX_VALUE)
                                    .addComponent(panelGlass15, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_payback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_cash, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelGlass16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelGlass14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass6Layout.createSequentialGroup()
                                .addComponent(txt_deinvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(panelGlass8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelGlass6Layout.setVerticalGroup(
            panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGlass8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass6Layout.createSequentialGroup()
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelGlass6Layout.createSequentialGroup()
                            .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_invoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(19, 19, 19))
                        .addGroup(panelGlass6Layout.createSequentialGroup()
                            .addComponent(btn_delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGlass6Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelGlass10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelGlass13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGlass6Layout.createSequentialGroup()
                        .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelGlass14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_cash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelGlass15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelGlass12, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelGlass18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelGlass17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_payback, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelGlass16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_deinvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout panelGlass1Layout = new javax.swing.GroupLayout(panelGlass1);
        panelGlass1.setLayout(panelGlass1Layout);
        panelGlass1Layout.setHorizontalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGlass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelGlass3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGlass6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass1Layout.setVerticalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelGlass2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelGlass1Layout.createSequentialGroup()
                        .addComponent(panelGlass3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelGlass6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        lbl_time.setForeground(new java.awt.Color(255, 255, 255));
        lbl_time.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_time.setFont(new java.awt.Font("GeosansLight", 0, 72));

        lbl_date.setForeground(new java.awt.Color(255, 255, 255));
        lbl_date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_date.setFont(new java.awt.Font("GeosansLight", 0, 18));

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button_logout.png"))); // NOI18N
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button_refresh_small.png"))); // NOI18N
        btn_refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(1214, 1214, 1214)
                        .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelGlass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(lbl_time, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(panelGlass1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1274, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        if (txt_search.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please input your keyword");
        } else {
            if (cmb_categories.getSelectedItem().equals("Code")) {
                String namaKolom[] = {"Code", "Title", "Author", "Publisher", "Price", "Discount", "Stock"};
                rs = db.fcSelectCommand(namaKolom, "books_data", "Code LIKE '" + txt_search.getText() + "' ");
                tbl_result.setModel(new ResultSetTableModel(rs));
            } else if (cmb_categories.getSelectedItem().equals("Title")) {
                String namaKolom[] = {"Code", "Title", "Author", "Publisher", "Price", "Discount", "Stock"};
                rs = db.fcSelectCommand(namaKolom, "books_data", "Title LIKE '%" + txt_search.getText() + "%' ");
                tbl_result.setModel(new ResultSetTableModel(rs));
            } else if (cmb_categories.getSelectedItem().equals("Author")) {
                String namaKolom[] = {"Code", "Title", "Author", "Publisher", "Price", "Discount", "Stock"};
                rs = db.fcSelectCommand(namaKolom, "books_data", "Author LIKE '%" + txt_search.getText() + "%' ");
                tbl_result.setModel(new ResultSetTableModel(rs));
            } else if (cmb_categories.getSelectedItem().equals("Publisher")) {
                String namaKolom[] = {"Code", "Title", "Author", "Publisher", "Price", "Discount", "Stock"};
                rs = db.fcSelectCommand(namaKolom, "books_data", "Publisher LIKE '%" + txt_search.getText() + "%' ");
                tbl_result.setModel(new ResultSetTableModel(rs));
            } else if (cmb_categories.getSelectedItem().equals("Price")) {
                String namaKolom[] = {"Code", "Title", "Author", "Publisher", "Price", "Discount", "Stock"};
                rs = db.fcSelectCommand(namaKolom, "books_data", "Price LIKE '" + txt_search.getText() + "' ");
                tbl_result.setModel(new ResultSetTableModel(rs));
            } else if (cmb_categories.getSelectedItem().equals("Discount")) {
                String namaKolom[] = {"Code", "Title", "Author", "Publisher", "Price", "Discount", "Stock"};
                rs = db.fcSelectCommand(namaKolom, "books_data", "Discount LIKE '" + txt_search.getText() + "' ");
                tbl_result.setModel(new ResultSetTableModel(rs));
            } else if (cmb_categories.getSelectedItem().equals("Stock")) {
                String namaKolom[] = {"Code", "Title", "Author", "Publisher", "Price", "Discount", "Stock"};
                rs = db.fcSelectCommand(namaKolom, "books_data", "Stock LIKE '" + txt_search.getText() + "' ");
                tbl_result.setModel(new ResultSetTableModel(rs));
            }
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_priceActionPerformed

    private void txt_authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_authorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_authorActionPerformed

    private void tbl_resultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_resultMouseClicked
        txt_code.setText(String.valueOf(tbl_result.getValueAt(tbl_result.getSelectedRow(), 0)));
        txt_title.setText(String.valueOf(tbl_result.getValueAt(tbl_result.getSelectedRow(), 1)));
        txt_author.setText(String.valueOf(tbl_result.getValueAt(tbl_result.getSelectedRow(), 2)));
        txt_publisher.setText(String.valueOf(tbl_result.getValueAt(tbl_result.getSelectedRow(), 3)));
        txt_price.setText(String.valueOf(tbl_result.getValueAt(tbl_result.getSelectedRow(), 4)));
        txt_discount.setText(String.valueOf(tbl_result.getValueAt(tbl_result.getSelectedRow(), 5)));
        cost();
    }//GEN-LAST:event_tbl_resultMouseClicked

    private void txt_amountInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_amountInputMethodTextChanged
    }//GEN-LAST:event_txt_amountInputMethodTextChanged

    private void btn_chartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chartActionPerformed
        if (txt_code.getText().equals("") || txt_title.getText().equals("") || txt_publisher.getText().equals("")
                || txt_price.getText().equals("") || txt_discount.getText().equals("") || txt_amount.getText().equals("") || txt_cost.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please input your data compleatly");
        } else if (txt_invoice.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please input the Invoice Number");
        } else {
            String[] kolom = {"Invoice", "Code", "Title", "Cost", "Amount", "Subtotal"};
            String[] isi = {txt_invoice.getText(), txt_code.getText(), txt_title.getText(), txt_cost.getText(), txt_amount.getText(), lbl_subtotal.getText()};
            System.out.println(db.queryInsert("chart", kolom, isi));
            try {
                if (!check_stock()) {
                    JOptionPane.showMessageDialog(this, "Stock is Limited");
                } else {
                    kurang();
                    table();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Transaction.class.getName()).log(Level.SEVERE, null, ex);
            }
            subtotal();
            tampil_chart();
            total();
        }


    }//GEN-LAST:event_btn_chartActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        Nota n = new Nota();
        n.setVisible(true);
        payback();
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        String id = String.valueOf(tbl_chart.getValueAt(tbl_chart.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(this, "Are you sure to delete this data", "Warning", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("chart", "ID=" + id);
        } else {
            return;
        }
        tampil_chart();
        total();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void txt_deinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deinvoiceActionPerformed
        String invoice = txt_invoice.getText();
        if (JOptionPane.showConfirmDialog(this, "Are you sure to delete this data", "Warning", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("chart", "Invoice=" + invoice);
        } else {
            return;
        }
        tampil_chart();
        total();
    }//GEN-LAST:event_txt_deinvoiceActionPerformed

    private void btn_delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete1ActionPerformed
        tampil_chart();
        total();
    }//GEN-LAST:event_btn_delete1ActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
}//GEN-LAST:event_btn_logoutActionPerformed

    private void txt_amountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_amountKeyReleased
        subtotal();
    }//GEN-LAST:event_txt_amountKeyReleased

    private void txt_cashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cashKeyReleased
        payback();
    }//GEN-LAST:event_txt_cashKeyReleased

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        table();
    }//GEN-LAST:event_btn_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public void cost() {
        double a = Double.parseDouble(txt_price.getText());
        double b = Double.parseDouble(txt_discount.getText());
        double c = a - a * (b / 100);
        txt_cost.setText(String.valueOf(c));
    }

    public void subtotal() {
        double a = Double.parseDouble(txt_cost.getText());
        double b = Double.parseDouble(txt_amount.getText());
        double c = a * b;
        lbl_subtotal.setText(String.valueOf(c));
    }

    public void total() {
        rs = db.eksekusiQuery("SELECT SUM(Subtotal) as subtotal FROM chart WHERE Invoice = '" + txt_invoice.getText() + "'");
        try {
            rs.next();
            lbl_total.setText(rs.getString("subtotal"));
        } catch (SQLException ex) {
            Logger.getLogger(Transaction.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public boolean check_stock() throws SQLException {
        boolean checkstock;
        rs = db.querySelectAll("books_data", "Code='" + txt_code.getText() + "'");
        while (rs.next()) {
            old = rs.getInt("Stock");
        }
        dec = Integer.parseInt(txt_amount.getText());
        if (old < dec) {
            checkstock = false;
        } else {
            checkstock = true;
        }
        return checkstock;
    }

    public void kurang() throws SQLException {
        rs = db.querySelectAll("books_data", "Code='" + txt_code.getText() + "'");
        while (rs.next()) {
            old = rs.getInt("Stock");
        }
        dec = Integer.parseInt(txt_amount.getText());
        now = old - dec;
        newstock = Integer.toString(now);

        String a = String.valueOf(newstock);
        String[] kolom = {"Stock"};
        String[] isi = {a};
        System.out.println(db.queryUpdate("books_data", kolom, isi, "Code='" + txt_code.getText() + "'"));
    }

    public void payback() {
        int a = Integer.parseInt(lbl_total.getText());
        int b = Integer.parseInt(txt_cash.getText());
        int c = b - a;
        txt_payback.setText(Integer.toString(c));
    }

    public void jam() {
        Date skrg = new Date();
        SimpleDateFormat tgl = new SimpleDateFormat("EEEE-dd-MMM-yyyy");
        SimpleDateFormat jam = new SimpleDateFormat("HH:mm");
        lbl_time.setText(jam.format(skrg));
        lbl_date.setText(tgl.format(skrg));
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Transaction().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static usu.widget.ButtonGlass btn_cancel;
    public static usu.widget.ButtonGlass btn_chart;
    public static usu.widget.ButtonGlass btn_delete;
    public static usu.widget.ButtonGlass btn_delete1;
    public static usu.widget.ButtonGlass btn_logout;
    public static usu.widget.ButtonGlass btn_print;
    public static usu.widget.ButtonGlass btn_refresh;
    public static usu.widget.ButtonGlass btn_search;
    public static javax.swing.JComboBox cmb_categories;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane2;
    public static usu.widget.Label label1;
    public static usu.widget.Label label10;
    public static usu.widget.Label label12;
    public static usu.widget.Label label13;
    public static usu.widget.Label label14;
    public static usu.widget.Label label15;
    public static usu.widget.Label label16;
    public static usu.widget.Label label18;
    public static usu.widget.Label label19;
    public static usu.widget.Label label2;
    public static usu.widget.Label label20;
    public static usu.widget.Label label21;
    public static usu.widget.Label label22;
    public static usu.widget.Label label23;
    public static usu.widget.Label label24;
    public static usu.widget.Label label25;
    public static usu.widget.Label label3;
    public static usu.widget.Label label4;
    public static usu.widget.Label label5;
    public static usu.widget.Label label6;
    public static usu.widget.Label label7;
    public static usu.widget.Label label8;
    public static usu.widget.Label label9;
    public static usu.widget.Label lbl_date;
    public static usu.widget.Label lbl_subtotal;
    public static usu.widget.Label lbl_time;
    public static usu.widget.Label lbl_total;
    public static usu.widget.Panel panel1;
    public static usu.widget.glass.PanelGlass panelGlass1;
    public static usu.widget.glass.PanelGlass panelGlass10;
    public static usu.widget.glass.PanelGlass panelGlass12;
    public static usu.widget.glass.PanelGlass panelGlass13;
    public static usu.widget.glass.PanelGlass panelGlass14;
    public static usu.widget.glass.PanelGlass panelGlass15;
    public static usu.widget.glass.PanelGlass panelGlass16;
    public static usu.widget.glass.PanelGlass panelGlass17;
    public static usu.widget.glass.PanelGlass panelGlass18;
    public static usu.widget.glass.PanelGlass panelGlass2;
    public static usu.widget.glass.PanelGlass panelGlass3;
    public static usu.widget.glass.PanelGlass panelGlass4;
    public static usu.widget.glass.PanelGlass panelGlass6;
    public static usu.widget.glass.PanelGlass panelGlass7;
    public static usu.widget.glass.PanelGlass panelGlass8;
    public static javax.swing.JTable tbl_chart;
    public static javax.swing.JTable tbl_result;
    public static usu.widget.TextBox txt_amount;
    public static usu.widget.TextBox txt_author;
    public static usu.widget.TextBox txt_cash;
    public static usu.widget.TextBox txt_code;
    public static usu.widget.TextBox txt_cost;
    public static usu.widget.ButtonGlass txt_deinvoice;
    public static usu.widget.TextBox txt_discount;
    public static usu.widget.TextBox txt_invoice;
    public static usu.widget.TextBox txt_payback;
    public static usu.widget.TextBox txt_price;
    public static usu.widget.TextBox txt_publisher;
    public static usu.widget.TextBox txt_search;
    public static usu.widget.TextBox txt_title;
    // End of variables declaration//GEN-END:variables
}
